# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/EGH400_1_Thesis/src/ip/tw_ram_cos/tw_ram_cos.xci
# IP: The module: 'tw_ram_cos' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EGH400_1_Thesis/src/ip/tw_ram_cos/tw_ram_cos_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tw_ram_cos'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/EGH400_1_Thesis/src/ip/tw_ram_cos/tw_ram_cos.xci
# IP: The module: 'tw_ram_cos' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EGH400_1_Thesis/src/ip/tw_ram_cos/tw_ram_cos_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tw_ram_cos'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
