# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/CLK_IP/CLK_IP.xci
# IP: The module: 'CLK_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/CLK_IP/CLK_IP_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_IP'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/CLK_IP/CLK_IP.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/CLK_IP/CLK_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/CLK_IP/CLK_IP.xci
# IP: The module: 'CLK_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/CLK_IP/CLK_IP_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/CLK_IP/CLK_IP.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/CLK_IP/CLK_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
