# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/EGH400_1_Thesis/src/constraints/arty.xdc

# XDC: C:/EGH400_1_Thesis/src/constraints/bitstream_flash_config.xdc

# IP: C:/EGH400_1_Thesis/src/ip/tw_ram_sin/tw_ram_sin.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tw_ram_sin || ORIG_REF_NAME==tw_ram_sin} -quiet] -quiet

# IP: C:/EGH400_1_Thesis/src/ip/tw_ram_cos/tw_ram_cos.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tw_ram_cos || ORIG_REF_NAME==tw_ram_cos} -quiet] -quiet
