# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_implementation_FFT.constraints/arty.xdc

# IP: ip/TW2_RAM/TW2_RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TW2_RAM || ORIG_REF_NAME==TW2_RAM} -quiet] -quiet

# IP: ip/TW_RAM/TW_RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TW_RAM || ORIG_REF_NAME==TW_RAM} -quiet] -quiet

# IP: ip/dsp_macro_0/dsp_macro_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# IP: ip/DFTBD_MEM8I/DFTBD_MEM8I.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM8I || ORIG_REF_NAME==DFTBD_MEM8I} -quiet] -quiet

# IP: ip/DFTBD_MEM7I/DFTBD_MEM7I.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM7I || ORIG_REF_NAME==DFTBD_MEM7I} -quiet] -quiet

# IP: ip/DFTBD_MEM6I/DFTBD_MEM6I.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM6I || ORIG_REF_NAME==DFTBD_MEM6I} -quiet] -quiet

# IP: ip/DFTBD_MEM5I/DFTBD_MEM5I.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM5I || ORIG_REF_NAME==DFTBD_MEM5I} -quiet] -quiet

# IP: ip/DFTBD_MEM4I/DFTBD_MEM4I.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM4I || ORIG_REF_NAME==DFTBD_MEM4I} -quiet] -quiet

# IP: ip/DFTBD_MEM3I/DFTBD_MEM3I.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM3I || ORIG_REF_NAME==DFTBD_MEM3I} -quiet] -quiet

# IP: ip/DFTBD_MEM2I/DFTBD_MEM2I.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM2I || ORIG_REF_NAME==DFTBD_MEM2I} -quiet] -quiet

# IP: ip/DFTBD_MEM1I_1/DFTBD_MEM1I.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM1I || ORIG_REF_NAME==DFTBD_MEM1I} -quiet] -quiet

# IP: ip/DFTBD_MEM7/DFTBD_MEM7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM7 || ORIG_REF_NAME==DFTBD_MEM7} -quiet] -quiet

# IP: ip/DFTBD_MEM6/DFTBD_MEM6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM6 || ORIG_REF_NAME==DFTBD_MEM6} -quiet] -quiet

# IP: ip/DFTBD_MEM5/DFTBD_MEM5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM5 || ORIG_REF_NAME==DFTBD_MEM5} -quiet] -quiet

# IP: ip/DFTBD_MEM4/DFTBD_MEM4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM4 || ORIG_REF_NAME==DFTBD_MEM4} -quiet] -quiet

# IP: ip/DFTBD_MEM3/DFTBD_MEM3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM3 || ORIG_REF_NAME==DFTBD_MEM3} -quiet] -quiet

# IP: ip/DFTBD_MEM8/DFTBD_MEM8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM8 || ORIG_REF_NAME==DFTBD_MEM8} -quiet] -quiet

# IP: ip/DFTBD_MEM2/DFTBD_MEM2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM2 || ORIG_REF_NAME==DFTBD_MEM2} -quiet] -quiet

# IP: ip/DFTBD_MEM1/DFTBD_MEM1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM1 || ORIG_REF_NAME==DFTBD_MEM1} -quiet] -quiet

# IP: ip/clk_wiz_0_3/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/TW2_RAM/TW2_RAM_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/TW_RAM/TW_RAM_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM8I/DFTBD_MEM8I_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM7I/DFTBD_MEM7I_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM6I/DFTBD_MEM6I_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM5I/DFTBD_MEM5I_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM4I/DFTBD_MEM4I_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM3I/DFTBD_MEM3I_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM2I/DFTBD_MEM2I_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM1I_1/DFTBD_MEM1I_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM7/DFTBD_MEM7_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM6/DFTBD_MEM6_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM5/DFTBD_MEM5_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM4/DFTBD_MEM4_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM3/DFTBD_MEM3_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM8/DFTBD_MEM8_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM2/DFTBD_MEM2_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM1/DFTBD_MEM1_ooc.xdc

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/REPOS/EGH400_1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
