# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/REPOS/EGH400-1/EGH400_1_Thesis/src/constraints/arty.xdc

# IP: C:/REPOS/EGH400-1/EGH400_1_Thesis/src/ip/dsp_macro_0/dsp_macro_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet
