# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/REPOS/EGH400-1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/DFTBD_MEM8I/DFTBD_MEM8I.xci
# IP: The module: 'DFTBD_MEM8I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/REPOS/EGH400-1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM8I/DFTBD_MEM8I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DFTBD_MEM8I'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/REPOS/EGH400-1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.srcs/sources_1/ip/DFTBD_MEM8I/DFTBD_MEM8I.xci
# IP: The module: 'DFTBD_MEM8I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/REPOS/EGH400-1/EGH400_1_Thesis/VHDL/initial/Initial_Implementation_FFT/Initial_Implementation_FFT.gen/sources_1/ip/DFTBD_MEM8I/DFTBD_MEM8I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DFTBD_MEM8I'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
