# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/REPOS/EGH400_1/VHDL/inital/iniital_2/project_3/project_3.srcs/sources_1/ip/DFTBD_MEM4/DFTBD_MEM4.xci
# IP: The module: 'DFTBD_MEM4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/REPOS/EGH400_1/VHDL/inital/iniital_2/project_3/project_3.gen/sources_1/ip/DFTBD_MEM4/DFTBD_MEM4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DFTBD_MEM4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/REPOS/EGH400_1/VHDL/inital/iniital_2/project_3/project_3.srcs/sources_1/ip/DFTBD_MEM4/DFTBD_MEM4.xci
# IP: The module: 'DFTBD_MEM4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/REPOS/EGH400_1/VHDL/inital/iniital_2/project_3/project_3.gen/sources_1/ip/DFTBD_MEM4/DFTBD_MEM4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DFTBD_MEM4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
