# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/projects/pdmfft/src/ip/bd_ram_r1/bd_ram_r1.xci
# IP: The module: 'bd_ram_r1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/projects/pdmfft/src/ip/bd_ram_r1/bd_ram_r1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ram_r1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FPGA/projects/pdmfft/src/ip/bd_ram_r1/bd_ram_r1.xci
# IP: The module: 'bd_ram_r1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/projects/pdmfft/src/ip/bd_ram_r1/bd_ram_r1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ram_r1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
