# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/REPOS/EGH400_1/EGH400-1 Thesis/VHDL/initial_2/arty.xdc

# IP: ip/TW_RAM/TW_RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TW_RAM || ORIG_REF_NAME==TW_RAM} -quiet] -quiet

# IP: ip/dsp_macro_0/dsp_macro_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# IP: ip/DFTBD_MEM1/DFTBD_MEM1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DFTBD_MEM1 || ORIG_REF_NAME==DFTBD_MEM1} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
